### ISSUE TITLE
mnist_client 连serving服务报错

### ISSUE THREAD

**Issue by lovejoy** [cheyang/tensorflow-sample-code#2]
按https://yq.aliyun.com/articles/603484 这个系列文章操作的 除了第三章中registry.aliyuncs.com/tensorflow-samples/tf-mnist-distributed:gpu  
这个镜像我换成了registry.aliyuncs.com/tensorflow-samples/tf-mnist-distributed:cpu

最终拿client去连serving的服务的时候，报错
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.FAILED_PRECONDITION, details="Serving signature key "serving_default" not found.")

**Comment by lovejoy** [comment]
结论：文章里面的镜像用的还是旧代码。poor guy。

**Comment by moonyoung430** [comment]
@lovejoy请问您最终是怎么解决的呢？我也遇到了这个问题。感谢
